### ISSUE TITLE
ToolTip Freezes when you Hover

### ISSUE THREAD

**Issue by johnmccurdy** [okviz/Candlestick#4]
Hi ,

I am hoping you can help me. I am using your Visualisation for Candlesticks in Power BI and recently have been having trouble when I hover over it to see the tooltip, I get an error. When I cancel this my tooltip stays static with the same data regardless of where I point it. I have tried

1.	Delete and re-install visualisation
2.	Create a brand new Power BI file and import the Candlestick visualisation
3.	Reduced my Dataset. PBIX file attached

I have emailed a sample pbix to your support email address.

When I copy the details from the Power BI Error I get

Feedback Type:
Frown (Error)

JS Error Message:
Error wrapper for thrown object: [{}]

Error Message:
An error occurred while rendering the report.

Stack Trace:
Error: Error wrapper for thrown object: [{}]
    at ms-pbi://pbi.microsoft.com/minerva/scripts/desktopUI.js:457:31
    at Scope.$apply (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:18018:11)
    at Array.flushOnChangesQueue (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:8227:20)
    at Scope.$digest (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:17806:55)
    at ms-pbi://pbi.microsoft.com/minerva/scripts/desktop.js:8194:43
    at SafeSubscriber.generatorOrNext.object.schedulerFn [as _next] (ms-pbi://pbi.microsoft.com/minerva/scripts/desktop.js:2665:21)
    at SafeSubscriber.__tryOrUnsub (ms-pbi://pbi.microsoft.com/minerva/scripts/desktop.js:4245:20)
    at SafeSubscriber.next (ms-pbi://pbi.microsoft.com/minerva/scripts/desktop.js:4219:144)
    at Subscriber._next (ms-pbi://pbi.microsoft.com/minerva/scripts/desktop.js:4196:30)
    at Subscriber.next (ms-pbi://pbi.microsoft.com/minerva/scripts/desktop.js:4188:36)

Stack Trace Message:
An error occurred while rendering the report.

Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.ClientShared.FeedbackErrorInfo..ctor(String message, Exception exception)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.ReportException(IWindowContainer activeWindow, WindowsHost windowsHost, FeedbackPackageInfo feedbackPackageInfo, Exception e, Boolean useGDICapture)
   at Microsoft.Mashup.Client.ClientShared.UnexpectedExceptionHandler.<>c__DisplayClass1.<HandleException>b__0()
   at Microsoft.Mashup.Host.Document.SynchronizationContextExtensions.<>c__DisplayClass3.<SendAndMarshalExceptions>b__0(Object null)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.ClientShared.WindowManager.ShowDialog[T](T form, IWindowContainer owner)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClassa.<Main>b__0()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<>c__DisplayClass7.<HandleExceptionsWithNestedTasks>b__6()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)

Model Default Mode:
Import

Snapshot Trace Logs:
C:\Users\JMcCurdy\AppData\Local\Microsoft\Power BI Desktop\FrownSnapShot1987304452.zip

Performance Trace Logs:
C:\Users\JMcCurdy\AppData\Local\Microsoft\Power BI Desktop\PerformanceTraces.zip

Disabled Preview Features:
PBI_shapeMapVisualEnabled
PBI_EnableReportTheme
PBI_numericSlicerEnabled
PBI_SpanishLinguisticsEnabled
CustomConnectors
PBI_AdobeAnalytics
PBI_qnaExplore
PBI_variationUIChange
PBI_customVisualsGallery
PBI_canvasTooltips

Disabled DirectQuery Options:
PBI_DirectQuery_Unrestricted
TreatHanaAsRelationalSource

Cloud:
GlobalCloud

Formulas:

section Section1;

shared Main = let
    Source = Sql.Database("abagri-nv-link-dev.database.windows.net", "Poultry", [Query="SELECT * #(lf)  FROM [dbo].[PoultryProductionData] WHERE FarmCode = '510066TEST5'"])
in
    Source;

shared PoultryFarmData = let
    Source = Sql.Database("abagri-nv-link-dev.database.windows.net", "Poultry", [Query="select * from [dbo].[PoultryFarmData] WHERE FarmCode = '510066TEST5'"])
in
    Source;

Active Section Contract:
{"id":0,"name":"ReportSection","displayName":"Temperature","filters":"[{\"name\":\"Filter\",\"expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Entity\":\"Main\"}},\"Property\":\"Age\"}},\"filter\":{\"Version\":2,\"From\":[{\"Name\":\"m\",\"Entity\":\"Main\"}],\"Where\":[{\"Condition\":{\"Comparison\":{\"ComparisonKind\":1,\"Left\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"m\"}},\"Property\":\"Age\"}},\"Right\":{\"Literal\":{\"Value\":\"0D\"}}}}}]},\"type\":\"Advanced\",\"howCreated\":1},{\"name\":\"Filter1\",\"expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Entity\":\"Main\"}},\"Property\":\"TempMin\"}},\"filter\":{\"Version\":2,\"From\":[{\"Name\":\"m\",\"Entity\":\"Main\"}],\"Where\":[{\"Condition\":{\"Comparison\":{\"ComparisonKind\":1,\"Left\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"m\"}},\"Property\":\"TempMin\"}},\"Right\":{\"Literal\":{\"Value\":\"0D\"}}}}}]},\"type\":\"Advanced\",\"howCreated\":1},{\"name\":\"Filter2\",\"expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Entity\":\"Main\"}},\"Property\":\"TempMax\"}},\"filter\":{\"Version\":2,\"From\":[{\"Name\":\"m\",\"Entity\":\"Main\"}],\"Where\":[{\"Condition\":{\"Comparison\":{\"ComparisonKind\":3,\"Left\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"m\"}},\"Property\":\"TempMax\"}},\"Right\":{\"Literal\":{\"Value\":\"100D\"}}}}}]},\"type\":\"Advanced\",\"howCreated\":1}]","ordinal":0,"visualContainers":[{"x":9.863013698630137,"y":19.726027397260275,"z":1,"width":1245.5577299412914,"height":627.0058708414873,"config":"{\"name\":\"a82e970a78cd4314787b\",\"layouts\":[{\"id\":0,\"position\":{\"x\":9.863013698630137,\"y\":19.726027397260275,\"z\":1,\"width\":1245.5577299412914,\"height\":627.0058708414873}}],\"singleVisual\":{\"visualType\":\"PBI_CV_886A053E_9DFD_4EA0_A47D_CCAEB89AF969\",\"projections\":{\"Category\":[{\"queryRef\":\"Main.Age\",\"active\":true}],\"open\":[{\"queryRef\":\"Sum(Main.TempMin)\"}],\"close\":[{\"queryRef\":\"Sum(Main.TempMax)\"}],\"high\":[{\"queryRef\":\"Sum(Main.TempMax)\"}],\"low\":[{\"queryRef\":\"Sum(Main.TempMin)\"}]},\"prototypeQuery\":{\"Version\":2,\"From\":[{\"Name\":\"m\",\"Entity\":\"Main\"}],\"Select\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"m\"}},\"Property\":\"Age\"},\"Name\":\"Main.Age\"},{\"Aggregation\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"m\"}},\"Property\":\"TempMin\"}},\"Function\":3},\"Name\":\"Sum(Main.TempMin)\"},{\"Aggregation\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"m\"}},\"Property\":\"TempMax\"}},\"Function\":4},\"Name\":\"Sum(Main.TempMax)\"}]},\"drillFilterOtherVisuals\":true}}","filters":"[]"}],"displayOption":1,"width":1280,"height":720,"config":"{}"}

Many Thanks

John

**Comment by danieleperilli** [comment]
The issue has been solved in v1.0.4. The update has been sent to Microsoft, but their review process could take up to 3 weeks. After this period, they will publish the new release in the AppSource and every report that uses an old version of the visual will be automatically updated. If you want to test it before, you can download the latest beta version from the our website: [Candlestick by OKViz](https://okviz.com/candlestick/)

**Comment by johnmccurdy** [comment]
Many Thanks for this. I have downloaded v1.0.4 manually, however still have the same issue after updating the visual in Power BI

**Comment by danieleperilli** [comment]
Have you downloaded the BETA? I tested your specific file in Power BI Desktop and the issue doesn't appear anymore, but you have to use BETA until the visual is not released in the marketplace, otherwise Power BI will downgrade it to the current version in the marketplace.

**Comment by johnmccurdy** [comment]
Hi Daniele, I had to delete the previous visual from the pbix file and when I then installed the BETA version all seems ok. Many Thanks for your help.
